export const ActionTypes = {
 GET_PRODUCTS : "GET_PRODUCTS",
 LOADING_PRODUCTS: "LOADING_PRODUCTS",
 CHANGE_ROLE: "CHANGE_ROLE",
 CHANGE_EXP :"CHANGE_EXP",
 CHANGE_SALARY : "CHANGE_SALARY",
 CHANGE_LOCATION :"CHANGE_LOCATION",
 COMPANY_NAME :"COMPANY_NAME"

}

export const baseURL = "https://api.weekday.technology/adhoc/getSampleJdJSON"